const SERVERL_BASE_URL = process.env.NEXT_PUBLIC_SERVER_URL;
const REDIRECT_URL = process.env.NEXT_PUBLIC_REDIRECT_URL;
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export { REDIRECT_URL, SERVERL_BASE_URL, SUPABASE_ANON_KEY, SUPABASE_URL };
