

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."ALLOCATIONS" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "project_id" "uuid" NOT NULL,
    "start_date" timestamp without time zone DEFAULT "now"() NOT NULL,
    "end_date" timestamp without time zone,
    "percentage" smallint DEFAULT '100'::smallint NOT NULL
);


ALTER TABLE "public"."ALLOCATIONS" OWNER TO "postgres";


COMMENT ON TABLE "public"."ALLOCATIONS" IS 'Describe the relation between users and projects';



CREATE TABLE IF NOT EXISTS "public"."PERMITS" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "duration" numeric NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "description" "text",
    "type" "text" DEFAULT 'Holiday'::"text" NOT NULL,
    "start_date" timestamp without time zone NOT NULL,
    "status" "text" DEFAULT 'Waiting'::"text" NOT NULL,
    "reviewer_id" "uuid" NOT NULL,
    "end_date" timestamp without time zone
);


ALTER TABLE "public"."PERMITS" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."PROJECTS" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "client" character varying NOT NULL,
    "description" "text",
    "start_date" timestamp without time zone NOT NULL,
    "end_date" timestamp without time zone,
    "status_id" "uuid" NOT NULL
);


ALTER TABLE "public"."PROJECTS" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ROLES" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "label" character varying NOT NULL
);


ALTER TABLE "public"."ROLES" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."STATUSES" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL
);


ALTER TABLE "public"."STATUSES" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."TIMESHEETS" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" "date" NOT NULL,
    "project_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "description" character varying
);


ALTER TABLE "public"."TIMESHEETS" OWNER TO "postgres";


ALTER TABLE "public"."TIMESHEETS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TIMESHEETS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."USERS" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text" NOT NULL,
    "name" "text" NOT NULL,
    "avatar_url" "text",
    "auth_id" character varying,
    "role_id" "uuid"
);


ALTER TABLE "public"."USERS" OWNER TO "postgres";


ALTER TABLE ONLY "public"."ALLOCATIONS"
    ADD CONSTRAINT "ALLOCATIONS_pkey" PRIMARY KEY ("user_id", "project_id");



ALTER TABLE ONLY "public"."PERMITS"
    ADD CONSTRAINT "PERMITS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."PROJECTS"
    ADD CONSTRAINT "PROJECTS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ROLES"
    ADD CONSTRAINT "ROLES_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."STATUSES"
    ADD CONSTRAINT "STATUS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."TIMESHEETS"
    ADD CONSTRAINT "TIMESHEETS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "USERS_auth_id_key" UNIQUE ("auth_id");



ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "USERS_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "USERS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ALLOCATIONS"
    ADD CONSTRAINT "ALLOCATIONS_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."PROJECTS"("id");



ALTER TABLE ONLY "public"."ALLOCATIONS"
    ADD CONSTRAINT "ALLOCATIONS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."USERS"("id");



ALTER TABLE ONLY "public"."PERMITS"
    ADD CONSTRAINT "PERMITS_reviewer_id_fkey" FOREIGN KEY ("reviewer_id") REFERENCES "public"."USERS"("id");



ALTER TABLE ONLY "public"."PERMITS"
    ADD CONSTRAINT "PERMITS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."USERS"("id");



ALTER TABLE ONLY "public"."PROJECTS"
    ADD CONSTRAINT "PROJECTS_status_id_fkey" FOREIGN KEY ("status_id") REFERENCES "public"."STATUSES"("id") ON UPDATE CASCADE ON DELETE SET DEFAULT;



ALTER TABLE ONLY "public"."TIMESHEETS"
    ADD CONSTRAINT "TIMESHEETS_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."PROJECTS"("id");



ALTER TABLE ONLY "public"."TIMESHEETS"
    ADD CONSTRAINT "TIMESHEETS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."USERS"("id");



ALTER TABLE ONLY "public"."USERS"
    ADD CONSTRAINT "USERS_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."ROLES"("id");



ALTER TABLE "public"."ALLOCATIONS" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."PERMITS" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."PROJECTS" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ROLES" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."STATUSES" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."TIMESHEETS" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."USERS" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






























































































































































































































GRANT ALL ON TABLE "public"."ALLOCATIONS" TO "anon";
GRANT ALL ON TABLE "public"."ALLOCATIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."ALLOCATIONS" TO "service_role";



GRANT ALL ON TABLE "public"."PERMITS" TO "anon";
GRANT ALL ON TABLE "public"."PERMITS" TO "authenticated";
GRANT ALL ON TABLE "public"."PERMITS" TO "service_role";



GRANT ALL ON TABLE "public"."PROJECTS" TO "anon";
GRANT ALL ON TABLE "public"."PROJECTS" TO "authenticated";
GRANT ALL ON TABLE "public"."PROJECTS" TO "service_role";



GRANT ALL ON TABLE "public"."ROLES" TO "anon";
GRANT ALL ON TABLE "public"."ROLES" TO "authenticated";
GRANT ALL ON TABLE "public"."ROLES" TO "service_role";



GRANT ALL ON TABLE "public"."STATUSES" TO "anon";
GRANT ALL ON TABLE "public"."STATUSES" TO "authenticated";
GRANT ALL ON TABLE "public"."STATUSES" TO "service_role";



GRANT ALL ON TABLE "public"."TIMESHEETS" TO "anon";
GRANT ALL ON TABLE "public"."TIMESHEETS" TO "authenticated";
GRANT ALL ON TABLE "public"."TIMESHEETS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TIMESHEETS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TIMESHEETS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TIMESHEETS_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."USERS" TO "anon";
GRANT ALL ON TABLE "public"."USERS" TO "authenticated";
GRANT ALL ON TABLE "public"."USERS" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
